### ISSUE TITLE
[Bug] copaw worker: active_skills/ updates from apply --zip don't propagate to workspaces/default/skills/, breaking skill hot-reload

### ISSUE THREAD

**Issue by hlgone** [agentscope-ai/HiClaw#712]
## Summary

`hiclaw apply worker --zip` against an **existing** copaw worker
updates the package in MinIO and the worker's `active_skills/`
directory, but **does not** sync those changes into
`workspaces/default/skills/<skill>/`. The LLM's `execute_shell_command`
tool invocations resolve to the workspace path, so user code / config
changes pushed via apply --zip are **invisible to the running agent**.

This is equivalent to "copaw workers cannot hot-reload skill code or
config after their first deploy" — a hard blocker for any skill that
needs to ship updates without recreating the worker.

## Environment

- HiClaw v1.1.0 GA, embedded mode, macOS Docker Desktop
- Worker: copaw runtime
- Skill: a custom skill (streetlight) with `scripts/_client.py` plus
  a non-secret `service.json` config file under `skills/<name>/`

## Reproduction

1. Create a copaw worker with package A (skill v1 in `skills/<name>/scripts/`)
2. `hiclaw apply worker --zip <pkg-A>.zip --name <worker>`; verify it works
3. Edit the skill code or add a new file (e.g. `service.json`)
4. `hiclaw apply worker --zip <pkg-B>.zip --name <worker>` (same worker name)
5. Inspect the container:

   ```
   docker exec hiclaw-worker-<name> ls /root/.hiclaw-worker/<name>/.copaw/active_skills/<skill>/
   docker exec hiclaw-worker-<name> ls /root/.hiclaw-worker/<name>/.copaw/workspaces/default/skills/<skill>/
   ```

   `active_skills/` reflects pkg B; `workspaces/default/skills/` is
   still pkg A.
6. Send a Matrix message that triggers the skill. **Observed in the
   agent's session JSON / tool trace** (not inferred): the agent calls
   `execute_shell_command` with a path under
   `workspaces/default/skills/<skill>/scripts/`, runs the **old** code,
   returns old output.

## Diagnostic evidence

The agent's session JSON (under
`<worker>/.copaw/workspaces/default/sessions/<room>.json`) shows the
resolved tool-call path:

```
"name": "execute_shell_command",
"input": {"command":
  "python3 /root/.hiclaw-worker/<name>/.copaw/workspaces/default/skills/<skill>/scripts/<x>.py"}
```

— always the workspace path, never the active_skills path.

`md5sum` confirms the two paths drift after any post-create apply --zip:

```
<active_skills hash>  active_skills/<skill>/scripts/_client.py
<workspaces hash>     workspaces/default/skills/<skill>/scripts/_client.py
```

## Workaround

```bash
docker exec <worker-container> sh -c \
  'cp -av /root/.hiclaw-worker/<name>/.copaw/active_skills/<skill>/. \
          /root/.hiclaw-worker/<name>/.copaw/workspaces/default/skills/<skill>/'
```

Effective immediately; agent picks up new code on next tool call. But
it's manual + per-container + needs to be re-run on every package
update.

## Suggested directions

- (a) On reconcile completion (post-merge), copaw should resync
  `workspaces/default/skills/<skill>/` from `active_skills/<skill>/`
  (or a single shared source). Most surgical.
- (b) Eliminate the duplicate copy entirely; `workspaces/default/skills/`
  could be a symlink / overlayfs view of `active_skills/`. Cleanest, but
  riskier if there are workspace-specific edits expected.
- (c) Add an explicit "skill resync" lifecycle hook the agent can call,
  documented in the skill update workflow.

(a) keeps the existing two-tier model but closes the sync gap.

## Severity

**High** for any production deployment with custom skills:

- skill bug fixes never reach the agent — operators must manually copy
  files inside the container or delete/recreate the worker, risking
  room/reconcile state and operational drift
- skill config files (`service.json`, `*.example`) added in updates
  are silently absent at runtime
- error reporting reflects the OLD code's error messages, masking
  whether a "service unavailable" reply is genuine or a stale-skill
  artifact

## Related

- HiClaw #711: AGENTS.md merge race during apply --zip update — same
  update path, separate issue

**Comment by johnlanni** [comment]
cc @maplefeng-a

**Comment by shiyiyue1102** [comment]
这里主分支看起来已经有对应修复：`sync_skills_to_runtime` 会把 `workspaces/default/skills` 链到标准空间 `skills/`，pull loop 检测到 `skills/` 变更后也会重新同步 runtime projection。相关提交是 `e84d460 fix(copaw): sync skills into workspace directory`。

麻烦用当前主分支，或包含这个提交的 `hiclaw-copaw-worker` 镜像复测一下：对已有 copaw worker 执行 `apply --zip` 更新 skill 后，确认 `skills/<name>/` 和 `workspaces/default/skills/<name>/` 是否都已经是最新内容，agent 的 tool call 是否能执行新代码。

如果主分支复测通过，这个 issue 后续可以随包含该修复的版本发布一起关闭；如果仍然复现，请补充使用的镜像 tag / commit，以及这两个目录的文件差异。

---
The main branch here seems to have corresponding fixes: `sync_skills_to_runtime` will link `workspaces/default/skills` to the standard space `skills/`, and the pull loop will also resynchronize the runtime projection after detecting the change of `skills/`. The related commit is `e84d460 fix(copaw): sync skills into workspace directory`.

Please use the current main branch or the `hiclaw-copaw-worker` image that contains this submission to retest: execute `apply --zip` on the existing copaw worker. After updating the skill, confirm whether `skills/<name>/` and `workspaces/default/skills/<name>/` are already up to date, and whether the agent's tool call can execute the new code.

If the main branch retest passes, this issue can be closed together with the release of the version containing the fix; if it still recurs, please add the image tag/commit used and the file differences between the two directories.

**Comment by hlgone** [comment]
Thanks for confirming and pointing to `e84d460`.

We tried to verify the referenced fix, but could not locate the commit/function in the public repos we checked. Could you help confirm the exact commit / repository?

What we checked:

1. GitHub API lookup for `e84d460` returned `No commit found` in:
   - `agentscope-ai/HiClaw`
   - `agentscope-ai/QwenPaw`
   - `agentscope-ai/CoPaw` (redirects to QwenPaw)
   - related `higress-group/*` repos we checked

2. Source search on current public `main` found no `sync_skills_to_runtime` symbol in HiClaw / QwenPaw.

3. In public HiClaw main, the CoPaw worker code appears to use `sync_skills_to_working_dir` from `copaw.agents.skills_manager`. The current `_sync_skills()` path still appears to write into `active_skills/`; we could not confirm the `workspaces/default/skills/` projection fix from the public source alone.

4. `copaw/AGENTS.md` in HiClaw main also says skill injection currently writes `active_skills/` directly and bypasses CoPaw's `skill_pool/` → `workspaces/default/skills/` reconcile flow. It also notes that the upstream CoPaw fork used by this project lives outside this repo.

So we may be looking at the wrong repo/commit, or the fix may live in the private/internal CoPaw fork rather than public HiClaw main.

Could you provide one of the following?

- the exact repository + full commit SHA containing the fix;
- a `hiclaw-copaw-worker` pre-release/nightly image containing the fix;
- or the canonical Dockerfile/build command that produces a worker image containing this fix from public `main`.

Once we have an image that actually contains the fix, we will run the full `apply --zip` retest and report back:

- image tag / commit
- `skills/<name>/`, `.copaw/active_skills/<name>/`, and `.copaw/workspaces/default/skills/<name>/` checksums and file contents before/after `apply --zip`
- deterministic workspace execution result
- optional agent tool-call behavior from session JSON

**Comment by shiyiyue1102** [comment]
Sorry for the confusion. The commit I mentioned earlier is not available in the public HiClaw repo, so it should not be used as evidence that public `main` already contains the fix.

We will keep this issue open and optimize the skill update sync path in the next HiClaw version. Once a public commit or image tag is available, we will ask you to retest the same `apply --zip` scenario.

**Comment by shiyiyue1102** [comment]
Update: this sync path has now landed on public main via #847. The CoPaw runtime now uses `sync_skills_to_runtime` to expose the standard `skills/` directory under `workspaces/default/skills/`, with bridge/sync tests added around that path.

Please retest the `apply --zip` skill hot-reload flow with a latest `hiclaw-copaw-worker` image that includes #847. If both `skills/<name>/` and `workspaces/default/skills/<name>/` contain the updated content, we can treat this issue as fixed by the merged PR. If it still does not sync, please share the image tag/digest and the diff between those two directories.

**Comment by hlgone** [comment]
Thanks for the update — glad to see #847 landed on public main.

Before we retest: the registry image `higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/hiclaw-copaw-worker:latest` is still at digest `sha256:796d67cd0215…` (built 2026-05-07), which predates #847 (merged 2026-05-23). `docker pull` confirms no new layers:

```
$ docker pull higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/hiclaw-copaw-worker:latest
Digest: sha256:796d67cd021579387c1c77f6eb682150fa203c5bd68c41d85459c740dc15f579
Status: Image is up to date
```

Could you push a `hiclaw-copaw-worker` image that includes #847 — ideally with an explicit tag (e.g. `:v1.1.2` or `:pr847`) so we can pin the retest to a known build?

In the meantime we'll attempt a local source build from current public main to pre-verify the `apply --zip` sync path. We'll report back with:

1. source-build results (whether `sync_skills_to_runtime` is present and functional)
2. `apply --zip` A→B retest with `skills/`, `active_skills/`, and `workspaces/default/skills/` checksums before/after
3. agent tool-call path verification from session JSON

Final closure verification will be against the official registry image once available.

**Comment by shiyiyue1102** [comment]
Thanks for checking the image digest. That is expected for now: #847 has landed on public main, but the official registry image containing this change has not been published yet.

We are planning to include this fix in HiClaw v1.1.2, which should be released soon. Once the v1.1.2 `hiclaw-copaw-worker` image is available, please retest the same `apply --zip` A→B flow against that tag so the verification is based on an official build rather than `latest` or a local source image.

**Comment by hlgone** [comment]
Sounds good — we'll hold off on the local source build and wait for the official v1.1.2 `hiclaw-copaw-worker` image.

Once the v1.1.2 tag is available in the registry, we'll run the full `apply --zip` A→B retest and report back with:

1. image tag + digest
2. `skills/`, `active_skills/`, `workspaces/default/skills/` checksums before/after
3. agent tool-call path from session JSON
4. `sync_skills_to_runtime` log output confirming the symlink

**Comment by hlgone** [comment]
## Retest: `hiclaw-copaw-worker:v1.1.2` — `sync_skills_to_runtime` verified

**Image**
- Tag: `higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/hiclaw-copaw-worker:v1.1.2`
- Digest: `sha256:2f274d37530975203e35c513808441b962be0319a71b839bd887b40ea93de486`
- CI: `Build Images` run [26493720817](https://github.com/agentscope-ai/HiClaw/actions/runs/26493720817) — completed success

**Function availability**

```
# v1.1.2 — OK
$ docker run --rm --entrypoint /opt/venv/copaw/bin/python3 .../hiclaw-copaw-worker:v1.1.2 \
    -c "from copaw_worker.bridge import sync_skills_to_runtime; print('OK')"
OK

# v1.1.1 (latest) — ImportError
$ docker run --rm --entrypoint /opt/venv/copaw/bin/python3 .../hiclaw-copaw-worker:latest \
    -c "from copaw_worker.bridge import sync_skills_to_runtime; print('OK')"
ImportError: cannot import name 'sync_skills_to_runtime' from 'copaw_worker.bridge'
```

**Simulated A→B skill upgrade test**

Setup: standard `skills/haopaw_artifact_write/` has version B; runtime `workspaces/default/skills/haopaw_artifact_write/` has a stale physical copy of version A (reproducing the pre-fix drift state).

```
=== BEFORE sync ===
workspace is_symlink: False
workspace version: A

=== AFTER sync_skills_to_runtime() ===
installed: ['haopaw_artifact_write']
workspace is_symlink: True
symlink target: ../../../standard/skills
workspace version: B
FILES_MATCH: True
VERSION_UPGRADED: True
RESULT: PASS
```

`sync_skills_to_runtime` correctly:
1. Removed the stale physical `workspaces/default/skills/` directory
2. Created a symlink `workspaces/default/skills/ → ../../../standard/skills`
3. Version B content immediately visible through the symlink

**Remaining verification**

The above confirms the function works in isolation inside the v1.1.2 image. We have not yet tested the full `apply --zip` flow through the controller (which triggers the entrypoint → bridge → `sync_skills_to_runtime` chain), because our controller is still on v1.1.1. We plan to verify this as part of a staged upgrade.

Based on the simulated test, the fix from #847 is confirmed present and functional in the official v1.1.2 image.

**Comment by shiyiyue1102** [comment]
Thanks for the detailed v1.1.2 verification. This confirms that the #847 runtime-side fix is present in the official `hiclaw-copaw-worker:v1.1.2` image and that `sync_skills_to_runtime` handles the stale workspace projection case correctly in isolation.

Please continue with the full controller-driven `apply --zip` A→B verification after the staged upgrade. If the test passes, please update this issue with the result in time, and we will close it as fixed by #847 / v1.1.2.

**Comment by hlgone** [comment]
## Full controller-driven `apply --zip` A→B retest on v1.1.2 — `sync_skills_to_runtime` workspace projection verified

We've completed the staged upgrade of our stack to v1.1.2-haopaw-pr729 (controller image: `hiclaw/hiclaw-embedded:v1.1.2-haopaw-pr729`, based on upstream v1.1.2 + #729 PUT humans route patch — coord-injection / sync_skills_to_runtime code paths unchanged) and ran the full controller-driven A→B `apply --zip` flow on a throwaway worker.

### Throwaway test setup

- Worker name: `worker-probe712-202605281930` (one-shot; deleted after the run)
- Skill name: `probe712` (one-shot)
- Worker image: `higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/hiclaw-copaw-worker:v1.1.2`
- Runtime: copaw
- pkg-A: `probe712/probe_marker.txt` contains `PROBE_VERSION=A`, md5=`6bf9b13c470c774565eeaffe34548b91`
- pkg-B: same path with `PROBE_VERSION=B` + a new file `B_only_file.txt` (proves multi-file projection), md5=`f9a0602416bc4a3c7c88b83f6e51b15b`

### Step 1 — pkg-A apply

```
$ hiclaw apply worker --name worker-probe712-202605281930 --zip /tmp/pkg-A.zip
  worker/worker-probe712-202605281930 created

# Wait ~45s for container provisioning, then verify:
$ docker exec hiclaw-worker-worker-probe712-202605281930 ls -la \
    /root/hiclaw-fs/agents/worker-probe712-202605281930/.copaw/workspaces/default/skills
lrwxrwxrwx 1 root root 15 May 28 11:30 skills -> ../../../skills

$ docker exec hiclaw-worker-worker-probe712-202605281930 cat \
    .../workspaces/default/skills/probe712/probe_marker.txt
PROBE_VERSION=A
content_hash_basis=A-rev1-deterministic
```

✅ Workspace `skills` is a symlink (not a physical copy). Content reachable via the symlink shows pkg-A.

### Step 2 — push pkg-B to the standard skill location

To isolate the `sync_skills_to_runtime` / workspace-symlink projection from the controller-side push path, we updated the standard skill location directly via MinIO `mc cp` (full simulation of "a new package version is now the standard"):

```
$ mc cp /tmp/probe_marker_B.txt \
    hiclaw/hiclaw-storage/agents/worker-probe712-202605281930/skills/probe712/probe_marker.txt
# 81B transferred in 00m00s

$ mc cat .../skills/probe712/probe_marker.txt | md5sum
f9a0602416bc4a3c7c88b83f6e51b15b  -      # = pkg-B md5
```

### Step 3 — verify workspace symlink reflects B (the key #712 invariant)

```
$ docker exec hiclaw-worker-worker-probe712-202605281930 ls -la \
    .../workspaces/default/skills
lrwxrwxrwx 1 root root 15 May 28 11:32 skills -> ../../../skills       # symlink intact

$ docker exec hiclaw-worker-worker-probe712-202605281930 readlink -f \
    .../workspaces/default/skills
/root/hiclaw-fs/agents/worker-probe712-202605281930/skills

$ docker exec hiclaw-worker-worker-probe712-202605281930 cat \
    .../workspaces/default/skills/probe712/probe_marker.txt
PROBE_VERSION=B
content_hash_basis=B-rev2-deterministic
new_field_only_in_B=true

$ docker exec hiclaw-worker-worker-probe712-202605281930 md5sum \
    .../workspaces/default/skills/probe712/probe_marker.txt
f9a0602416bc4a3c7c88b83f6e51b15b  ...

$ docker exec hiclaw-worker-worker-probe712-202605281930 cat \
    .../workspaces/default/skills/probe712/B_only_file.txt
This file exists only in pkg-B (proves version B content reaches the workspace).
```

✅ Workspace symlink is preserved across update.
✅ Updated standard content is immediately visible through the symlink (no stale projection).
✅ Newly-added file in the standard location is also visible through the symlink.

### `sync_skills_to_runtime` signature in the official v1.1.2 image

```
$ docker exec ... /opt/venv/copaw/bin/python3 -c \
    'from copaw_worker.bridge import sync_skills_to_runtime; help(sync_skills_to_runtime)'

sync_skills_to_runtime(standard_dir: 'Path', runtime_dir: 'Path', skill_names: 'list[str]') -> 'list[str]'
    Expose Manager-pushed skills in CoPaw runtime space via symlink.
```

### Cleanup

Worker CR deleted, container removed, MinIO `agents/worker-probe712-202605281930/` prefix empty.

### Conclusion

From this side, the #847 / v1.1.2 runtime-side fix for #712 is **confirmed end-to-end**: a workspace projection no longer goes stale because it is implemented as a symlink to the standard skill location, and standard-location updates are immediately reflected in CoPaw's runtime view. Happy to have this closed as fixed by #847 / v1.1.2.

### Side note — separate from #712

While running the A→B flow above, we noticed that re-applying with `hiclaw apply worker --zip pkg-B.zip --name <same-worker>` only **added** new files (e.g. `B_only_file.txt`) to MinIO `agents/<worker>/skills/<skill>/`. **Existing files were not overwritten** — `probe_marker.txt` in MinIO retained the pkg-A content + pkg-A mtime even though pkg-B contained an updated version. We bypassed this with direct `mc cp` (Step 2) and the workspace-symlink projection then worked correctly.

This appears to be a separate issue in the controller's `apply --zip` content-replace semantics; it's not relevant to #712's workspace drift fix. Happy to file as a separate issue with full repro if useful. Let me know if the controller-side push path is supposed to overwrite-on-content-change for existing files in the package.

**Comment by RerankerGuo** [comment]
Opened PR #981 for this: https://github.com/agentscope-ai/AgentTeams/pull/981

The change restores the CoPaw standard-to-runtime bridge helpers and refreshes `.copaw/workspaces/default/skills` plus `skill.json` whenever Manager-pushed skills are pulled, so `apply --zip` updates become visible without a worker restart.

Verified locally with:
- `python3 -m py_compile copaw/src/copaw_worker/bridge.py copaw/src/copaw_worker/worker.py`
- `PYTHONPATH=/tmp/agentteams-pytest:copaw/src python3 -m pytest copaw/tests/test_bridge.py copaw/tests/test_sync.py` (45 passed)
- `git diff --check`
